### ISSUE TITLE
[Feature Request]:`.first` and `.last` attributes

### ISSUE THREAD

**Issue by JoFrhwld** [Forced-Alignment-and-Vowel-Extraction/alignedTextGrid#124]
### What feature would you like added?

For any given indexable class, `.first` and `.last` attributes could be useful to avoid needing to index.

possible implementation:

```python
@property
def first(self):
   return self.sequence_list[0]
   #return self.subset_list[0]
 
@property
def last(self):
   return self.sequence_list[-1]
```

### What would the use case be for this feature?

In `fave_recode`, I'm restricting the kinds of attributes people can access in the yaml specification. This would allow people to target a vowel in context of a the following word's onset like so

```yaml
- rule: followed-by-l
  conditions:
    # is ey
    - attribute: label
      relation: contains
      set: EY
    # is final
    - attribute: fol.label
      relation: ==
      set: "#"
    # first segment of following word is L
    - attribute: inword.fol.first
      relation: ==
      set: L
```

### Would you like to help add this feature?

Yes, and I will submit a pull request soon.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
